### PR TITLE
Add final conference schedule + speakers

### PR DESCRIPTION
**Pull request by Mohyiay**
- Add complete conference schedule
- Add latest speakers
- New CTA
- Adapted animated text banner (demo-1)

### CODE REVIEW

**Comment by jbelien** [comment]
@Mohyiay Can you make sure the linting passes ?

**Comment by jbelien** [comment]
Side note: I see that Olivier Van D'huynslager is a speaker but I don't see any talk by him.

**Comment by Mohyiay** [comment]
> Side note: I see that Olivier Van D'huynslager is a speaker but I don't see any talk by him.

We received a proposal for a keynote, but it changed to an Open Data bike ride of 2/3hrs after lunch.
It will be with Olivier Van D'huynslager, Leen Van Campe, Pieter-Jan Pauwels

Olivier can stay in the line-up and I will add Leen and Pieter-Jan.

**Review by jbelien — COMMENTED** [review]
Can't approve it since it's unusable on mobile and design could be improved.
Validated by Thimo so I'll merge it.

**Pull request merged**
