### PR TITLE
Added Mono as a partner

### PR DESCRIPTION
**Pull request by SteenackersAstrid**
-Added the logo of Mono
-Added the link to their website

Question: Mono is the biggest sponsor so far of Open Belgium. They should be the first logo on the first line. 
How do I create this first line (we have 3 partner tiers, for now we only have 2 in use)?

### CODE REVIEW

**Comment by jbelien** [comment]
> How do I create this first line (we have 3 partner tiers, for now we only have 2 in use)?

You should be able to split logos in lines by adding a `<br>` after the logo of Mono.
But maybe @mariedevos has a more elegant solution :P

**Review by jbelien — CHANGES_REQUESTED** [review]
@SteenackersAstrid The logo of Mono need to be changed (check the [preview](https://deploy-preview-30--openbelgium-2021.netlify.app/)).

**Comment by mariedevos** [comment]
@SteenackersAstrid you forgot to add width="150px" :)

**Comment by jbelien** [comment]
@SteenackersAstrid I would maybe ask the logo without the white background for consistency with the other logos.

**Comment by SteenackersAstrid** [comment]
@mariedevos : How do I create a second line of partners? I tried to add <br> after the mono logo but that failed.
And are the logos centered? 

It should be:
MONO
OKBE EWI Redpencil

**Comment by jbelien** [comment]
Nice, thanks @mariedevos 👍 

@SteenackersAstrid Do you validate the [preview](https://deploy-preview-30--openbelgium-2021.netlify.app/) ?

**Comment by SteenackersAstrid** [comment]
@jbelien , I do!

**Pull request merged**
