### PR TITLE
Update partners

### PR DESCRIPTION
**Pull request by Mohyiay**
Remove Abb

### CODE REVIEW

**Review by mietcls — APPROVED** [review]
Thanks! Btw, no need to throw away the files as they have been a long time loyal and important sponsor of ours – they might sponsor again.

**Review by jbelien — CHANGES_REQUESTED** [review]
I've made a small update to keep OKBE on a separated line since we're a "special" "partner" 😄 

Could you remove/undo the changes made on `package-lock.json` file ?
This is only about update the partners.

**Comment by jbelien** [comment]
> Btw, no need to throw away the files as they have been a long time loyal and important sponsor of ours – they might sponsor again.

Let's keep everything clean!
It makes sense to remove the logo if it's not used.
If we need the logo, it's still available in `2021` branch.

**Comment by Mohyiay** [comment]
I have undone the changes to the `package-lock.json` file 
Content wise change in the program section: `Programme` to `Meetup Program`

**Comment by jbelien** [comment]
> I have undone the changes to the `package-lock.json` file

I still see the `package-lock.json` changed in this PR.

**Comment by Mohyiay** [comment]
> > I have undone the changes to the `package-lock.json` file
> 
> I still see the `package-lock.json` changed in this PR.

Now it's corrected. (I double-checked this time)

**Review by jbelien — APPROVED** [review]

**Pull request merged**
